"""
signal_analysis package.

Reusable signal-analysis toolkit for indicators, transforms, topology,
filters, adapters, utils, and radar-oriented feature extraction.
"""

from signal_analysis.core import (
    build_feature_contract,
    infer_time_column,
    validate_dataframe,
    validate_numeric_columns,
    validate_ohlc_columns,
    validate_required_columns,
    # feature_window
    WINDOW_META_KEYS,
    WINDOW_SECTION_KEYS,
    build_empty_window,
    build_window_meta,
    build_windowed_sequence,
    extract_window_from_dataframe,
    validate_window,
    # sync
    align_channels,
    align_to_index,
    compute_coverage_ratio,
    compute_missing_ratio,
    diagnose_alignment,
    merge_channels,
    # window_builder
    WindowBuilder,
    build_feature_sections,
    build_window,
    build_window_sequence,
    flatten_window,
    summarize_frame,
    windows_to_feature_frame,
    # feature_pipeline
    FeaturePipeline,
    build_feature_matrix,
    build_pipeline_report,
    drop_non_numeric_features,
    fill_feature_matrix,
    validate_feature_matrix,
)
from signal_analysis.adapters import (
    series_to_ohlc_dataframe,
    series_to_ohlc_windows,
)
from signal_analysis.filters import (
    kalman_filter_1d,
    kalman_filter_multivariate,
    kalman_filter_ohlc,
)
from signal_analysis.indicators import (
    add_ohlc_geometry_features,
    classify_ohlc_geometry,
    compute_adx,
    compute_atr,
    compute_bollinger_bands,
    compute_directional_indicators,
    compute_ema,
    compute_kama,
    compute_macd,
    compute_macd_components,
    compute_macd_hist,
    compute_macd_signal,
    compute_minus_di,
    compute_ohlc_geometry,
    compute_plus_di,
    compute_roc,
    compute_rsi,
    compute_sma,
    compute_stochastic,
    compute_stochastic_signal,
    compute_stochrsi,
    compute_stochrsi_d,
    compute_stochrsi_k,
    compute_tr,
    compute_tsi,
    compute_williams_r,
    compute_wma,
    # invariants
    add_invariant_features,
    compute_local_ratio,
    compute_log_ratio,
    compute_minmax_position,
    compute_normalized_energy,
    compute_relative_change,
    compute_robust_zscore,
    compute_rolling_energy,
    compute_rolling_zscore,
    # dynamics
    add_dynamics_features,
    compute_acceleration,
    compute_curvature,
    compute_dynamic_profile,
    compute_jerk,
    compute_velocity,
    # states
    build_signal_state_frame,
    compute_activity_state,
    compute_momentum_state,
    compute_slope_state,
    compute_structure_state,
    compute_trend_state,
    compute_volatility_state,
)
from signal_analysis.microstructures import (
    compute_md_proxy_features,
    micro_doppler_features_placeholder,
    pairwise_distance_matrix,
    rolling_wasserstein_profile,
    sliding_window_embedding,
    wasserstein_distances,
    wasserstein_like_distance,
    wasserstein_regime_signal,
)
from signal_analysis.transforms import (
    compute_fft_magnitude,
    compute_fft_power_spectrum,
    compute_haar_wavelet_decomposition,
    compute_wavelet_energy,
    dominant_frequency,
    fft_feature_summary,
    moving_window_energy,
    spectral_centroid,
    spectral_energy,
    wavelet_energy_placeholder,
)
from signal_analysis.signals import (
    detectar_compra,
    detectar_venta,
    high_volume,
    stop_loss_take_profit,
)
from signal_analysis.utils import (
    cross_above,
    cross_below,
    cross_level_down,
    cross_level_up,
    ema_series,
    to_series,
    true_range,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "validate_dataframe",
    "validate_required_columns",
    "validate_numeric_columns",
    "validate_ohlc_columns",
    "infer_time_column",
    "build_feature_contract",
    "compute_sma",
    "compute_ema",
    "compute_wma",
    "compute_kama",
    "compute_rsi",
    "compute_tsi",
    "compute_roc",
    "compute_bollinger_bands",
    "compute_tr",
    "compute_atr",
    "compute_macd_components",
    "compute_macd",
    "compute_macd_signal",
    "compute_macd_hist",
    "compute_plus_di",
    "compute_minus_di",
    "compute_adx",
    "compute_directional_indicators",
    "compute_stochastic",
    "compute_stochastic_signal",
    "compute_williams_r",
    "compute_stochrsi",
    "compute_stochrsi_k",
    "compute_stochrsi_d",
    "compute_ohlc_geometry",
    "classify_ohlc_geometry",
    "add_ohlc_geometry_features",
    # invariants
    "compute_rolling_zscore",
    "compute_robust_zscore",
    "compute_local_ratio",
    "compute_log_ratio",
    "compute_relative_change",
    "compute_rolling_energy",
    "compute_normalized_energy",
    "compute_minmax_position",
    "add_invariant_features",
    # dynamics
    "compute_velocity",
    "compute_acceleration",
    "compute_jerk",
    "compute_curvature",
    "compute_dynamic_profile",
    "add_dynamics_features",
    # states
    "compute_slope_state",
    "compute_trend_state",
    "compute_momentum_state",
    "compute_volatility_state",
    "compute_structure_state",
    "compute_activity_state",
    "build_signal_state_frame",
    # core feature_window
    "WINDOW_SECTION_KEYS",
    "WINDOW_META_KEYS",
    "build_window_meta",
    "build_empty_window",
    "extract_window_from_dataframe",
    "validate_window",
    "build_windowed_sequence",
    # core sync
    "align_to_index",
    "align_channels",
    "compute_coverage_ratio",
    "compute_missing_ratio",
    "diagnose_alignment",
    "merge_channels",
    # core window_builder
    "WindowBuilder",
    "summarize_frame",
    "build_feature_sections",
    "build_window",
    "build_window_sequence",
    "flatten_window",
    "windows_to_feature_frame",
    # core feature_pipeline
    "FeaturePipeline",
    "build_feature_matrix",
    "validate_feature_matrix",
    "drop_non_numeric_features",
    "fill_feature_matrix",
    "build_pipeline_report",
    "to_series",
    "ema_series",
    "true_range",
    "cross_above",
    "cross_below",
    "cross_level_up",
    "cross_level_down",
    "series_to_ohlc_windows",
    "series_to_ohlc_dataframe",
    "compute_fft_magnitude",
    "compute_fft_power_spectrum",
    "dominant_frequency",
    "spectral_energy",
    "spectral_centroid",
    "fft_feature_summary",
    "moving_window_energy",
    "compute_haar_wavelet_decomposition",
    "compute_wavelet_energy",
    "wavelet_energy_placeholder",
    "sliding_window_embedding",
    "pairwise_distance_matrix",
    "wasserstein_like_distance",
    "rolling_wasserstein_profile",
    "wasserstein_regime_signal",
    "wasserstein_distances",
    "kalman_filter_1d",
    "kalman_filter_multivariate",
    "kalman_filter_ohlc",
    "micro_doppler_features_placeholder",
    "compute_md_proxy_features",
    "detectar_compra",
    "detectar_venta",
    "high_volume",
    "stop_loss_take_profit",
]
